#!/bin/bash

#docker image build . -t java_gpu_test --build-arg SharedDir=testABC

docker run --gpus all -it --rm \
-v runvol:/app \
-v testvol:/testABC \
-v mavenPackages:/root/.m2/repository \
java_gpu_test:latest

