#!/bin/bash

#docker image build . -t java_gpu_test --build-arg SharedDir=testABC

docker run --gpus all -it --rm \
-v run_data_volume:/app \
-v save_data_volume:/save \
-v mavenPackages:/root/.m2/repository \
java_gpu_test:latest

